database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT:-5432}
  name: ${DATABASE_NAME}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  pool_size: ${DATABASE_POOL_SIZE:-20}
  max_overflow: ${DATABASE_MAX_OVERFLOW:-30}
  ssl_mode: require
  
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT:-6379}
  db: ${REDIS_DB:-0}
  password: ${REDIS_PASSWORD}
  ssl: true
  
mongodb:
  host: ${MONGODB_HOST}
  port: ${MONGODB_PORT:-27017}
  name: ${MONGODB_NAME}
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}
  ssl: true